### ISSUE TITLE
SSL Credentials in source control

### ISSUE THREAD

**Issue by smithcoin** [ulukma/oolooq#1]
Your SSL certificate information (including your private key) is in the source control of this repository. Anybody can spoof your credentials. 

From Github's own source: 
> Warning: Once you have pushed a commit to GitHub, you should consider any data it contains to be compromised

You can take the steps mentioned in [this article](https://help.github.com/articles/removing-sensitive-data-from-a-repository/), but I would probably delete this repository and regenerate any relevant credentials.

**Comment by ulukma** [comment]
I see. Thank you for your time.
